### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by domenkozar** [batterseapower/parallel-io#11]
When I started Haskell, I've used this library and only a few months later discovered that go-to library nowadays is http://hackage.haskell.org/package/async

It would help to add a few words on that in the README, that this package was a great milestone in the evolution of parallel IO, but it's not the recommended solution now.

**Comment by batterseapower** [comment]
I don't know anything about that package, but I added a README to this repo pointing to it.

**Comment by ulysses4ever** [comment]
@batterseapower would it be possible to add the same note as in README to the cabal file's description field? Many people only look at Hackage and don't get to the GitHub repo, especially given that the Homepage link there is broken. I can submit a PR if you think it makes sense.
