### ISSUE TITLE
Too strict bound on random

### ISSUE THREAD

**Issue by sternenseemann** [batterseapower/parallel-io#14]
In case this is still maintained: parallel-io would build with random 1.2.0, but the upper version bound forbids it.

**Comment by batterseapower** [comment]
Happy to release an update: hopefully https://hackage.haskell.org/package/parallel-io-0.3.4 works for you

**Comment by sternenseemann** [comment]
Now I'm having trouble with containers instead…

**Comment by batterseapower** [comment]
OK, so maybe https://hackage.haskell.org/package/parallel-io-0.3.5 will work for you.

It was never completely clear to me that specifying tight upper bounds like this was actually a good idea given that most major version changes don't actually break anything, but it was considered good style at the time I built this package.

**Comment by sternenseemann** [comment]
Yes, thank you! Upper PVP-bounds are really a double edged sword…
