### ISSUE TITLE
Suggestion: Return the first result of a set of parallel computations, discarding the rest.

### ISSUE THREAD

**Issue by ppetr** [batterseapower/parallel-io#4]
For one project I needed a function that searches for existence of some objects in parallel. It needed to runs several computations in parallel If a result is found, all running or queued computations should be discarded. Your library seems to be almost what I needed, except that it doesn't allow to discard the remaining computations. Do you think it would be possible/difficult to add such a function? The type could be something like this:

```
parallelFirst :: Pool -> [IO (Maybe a)] -> IO (Maybe a)
```

The question is how to handle exceptions. Either they can be discarded just like if the failed computation returned `Nothing`, or any exception could be forwarded to `paralellFirst`.

**Comment by qrilka** [comment]
I wonder why this issue isn't closed yet when the fix was released quite long ago
